/**
 * 50-State Area Expert Profiles
 * ==============================
 * Each state gets local intelligence context injected into the edge model.
 * Tax rates, assessment ratios, cap rate ranges, major markets, key operators.
 *
 * This is the area expert. The model doesn't hallucinate local knowledge —
 * we GIVE it the local knowledge as structured context.
 */

export const STATES = {
  AL: {
    name: 'Alabama',
    property_tax_rate: 0.0041,
    assessment_ratio: 0.10,
    income_tax: true,
    markets: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery'],
    industrial_hubs: ['Huntsville (aerospace/defense)', 'Birmingham (distribution)', 'Mobile (port/shipbuilding)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: ['Prologis', 'Liberty Property'],
    notes: 'Low property taxes. Huntsville is a top growth market — Mazda-Toyota, Blue Origin, FBI ops center. Port of Mobile for logistics.',
  },
  AK: {
    name: 'Alaska',
    property_tax_rate: 0.0119,
    assessment_ratio: 1.0,
    income_tax: false,
    markets: ['Anchorage', 'Fairbanks'],
    industrial_hubs: ['Anchorage (cold storage, distribution)'],
    cap_rate_range: [0.075, 0.095],
    key_operators: [],
    notes: 'Limited industrial market. Cold storage and resource extraction dominate. High construction costs.',
  },
  AZ: {
    name: 'Arizona',
    property_tax_rate: 0.0062,
    assessment_ratio: 0.165,  // commercial
    income_tax: true,
    markets: ['Phoenix', 'Tucson', 'Mesa', 'Chandler'],
    industrial_hubs: ['Phoenix West Valley (mega-distribution)', 'Chandler (semiconductor)', 'Goodyear/Buckeye (logistics)'],
    cap_rate_range: [0.050, 0.070],
    key_operators: ['Prologis', 'VanTrust', 'Lincoln Property', 'Tratt Properties', 'Wentworth Property'],
    notes: 'Phoenix is top-3 US industrial market. TSMC fab in North Phoenix. Massive spec development. 330M+ SF industrial inventory.',
  },
  AR: {
    name: 'Arkansas',
    property_tax_rate: 0.0063,
    assessment_ratio: 0.20,
    income_tax: true,
    markets: ['Little Rock', 'Bentonville/NW Arkansas', 'Fort Smith'],
    industrial_hubs: ['NW Arkansas (Walmart HQ supply chain)', 'Little Rock (distribution)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: ['Walmart Real Estate'],
    notes: 'Walmart ecosystem drives NW Arkansas industrial. Last-mile for Walmart vendors.',
  },
  CA: {
    name: 'California',
    property_tax_rate: 0.0073,
    assessment_ratio: 1.0,  // Prop 13: assessed at purchase, 2% annual cap
    income_tax: true,
    markets: ['Los Angeles', 'Inland Empire', 'San Francisco', 'San Diego', 'Oakland', 'Sacramento', 'Orange County'],
    industrial_hubs: ['Inland Empire (largest US industrial market)', 'LA South Bay (port-adjacent)', 'Central Valley (cold storage/ag)', 'East Bay (port of Oakland)'],
    cap_rate_range: [0.038, 0.055],
    key_operators: ['Prologis', 'Rexford Industrial', 'CBRE Investment', 'Blackstone', 'Link Logistics'],
    notes: 'Prop 13 caps reassessment at 2%/yr — long-held properties have massive tax basis difference. Inland Empire is #1 US industrial market by absorption. Rexford is CA-only REIT. Extremely tight vacancy <2% in infill markets.',
  },
  CO: {
    name: 'Colorado',
    property_tax_rate: 0.0051,
    assessment_ratio: 0.29,
    income_tax: true,
    markets: ['Denver', 'Colorado Springs', 'Aurora', 'Boulder'],
    industrial_hubs: ['Denver I-70 corridor', 'DIA area (e-commerce)', 'Colorado Springs (defense/tech)'],
    cap_rate_range: [0.050, 0.065],
    key_operators: ['Prologis', 'Westcore Properties', 'Hines'],
    notes: 'Denver I-70 corridor is primary industrial. DIA area seeing massive spec development. Gallagher Amendment affects commercial assessment ratio.',
  },
  CT: {
    name: 'Connecticut',
    property_tax_rate: 0.0211,
    assessment_ratio: 0.70,
    income_tax: true,
    markets: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport'],
    industrial_hubs: ['I-91 corridor (distribution)', 'I-95 corridor (last-mile)'],
    cap_rate_range: [0.060, 0.080],
    key_operators: ['Prologis', 'STAG Industrial'],
    notes: 'Highest property taxes in US. Legacy manufacturing converting to last-mile. Hartford insurance corridor.',
  },
  DE: {
    name: 'Delaware',
    property_tax_rate: 0.0057,
    assessment_ratio: 0.60,
    income_tax: true,
    markets: ['Wilmington', 'Dover', 'Newark'],
    industrial_hubs: ['I-95 corridor (mid-Atlantic distribution)'],
    cap_rate_range: [0.060, 0.075],
    key_operators: ['Prologis', 'Liberty Property'],
    notes: 'No sales tax. Delaware River port access. Small market but strategic I-95 location between Philly and Baltimore.',
  },
  FL: {
    name: 'Florida',
    property_tax_rate: 0.0089,
    assessment_ratio: 1.0,
    income_tax: false,
    markets: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'West Palm Beach'],
    industrial_hubs: ['Miami-Dade (port/LatAm trade)', 'Orlando I-4 corridor', 'Jacksonville (port/rail)', 'Tampa I-75 corridor'],
    cap_rate_range: [0.048, 0.065],
    key_operators: ['Prologis', 'EastGroup', 'Foundry Commercial', 'Butters Group'],
    notes: 'No state income tax — major migration driver. PortMiami and JAXPORT drive logistics. South FL vacancy <3%. Insurance costs rising (hurricane risk). Save Our Homes caps homestead reassessment but NOT commercial.',
  },
  GA: {
    name: 'Georgia',
    property_tax_rate: 0.0092,
    assessment_ratio: 0.40,
    income_tax: true,
    markets: ['Atlanta', 'Savannah', 'Augusta'],
    industrial_hubs: ['Atlanta South (mega-distribution)', 'Savannah (port)', 'Atlanta I-20 West corridor'],
    cap_rate_range: [0.050, 0.070],
    key_operators: ['Prologis', 'Stonemont Financial', 'Seefried Industrial', 'Panattoni'],
    notes: 'Atlanta is top-5 US industrial market. Port of Savannah is fastest-growing US port. Massive spec development in South Atlanta. Hartsfield-Jackson drives air cargo.',
  },
  HI: {
    name: 'Hawaii',
    property_tax_rate: 0.0028,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Honolulu', 'Maui'],
    industrial_hubs: ['Kapolei/Ewa (Oahu industrial)', 'Sand Island'],
    cap_rate_range: [0.045, 0.060],
    key_operators: [],
    notes: 'Extremely limited industrial supply. Island constraints mean near-zero new development. Lowest property tax rate in US.',
  },
  ID: {
    name: 'Idaho',
    property_tax_rate: 0.0063,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Boise', 'Nampa', 'Meridian'],
    industrial_hubs: ['Boise (tech/distribution)', 'Nampa (food processing)'],
    cap_rate_range: [0.055, 0.075],
    key_operators: ['Prologis'],
    notes: 'Boise is a growth market — Micron, HP legacy. Limited institutional industrial supply.',
  },
  IL: {
    name: 'Illinois',
    property_tax_rate: 0.0197,
    assessment_ratio: 0.33,
    income_tax: true,
    markets: ['Chicago', 'Rockford', 'Joliet', 'Aurora'],
    industrial_hubs: ['I-80 corridor (mega-distribution)', 'I-55 corridor', 'OHare area (air cargo)', 'I-88 corridor'],
    cap_rate_range: [0.055, 0.075],
    key_operators: ['Prologis', 'CenterPoint Properties', 'Bridge Industrial', 'Hillwood'],
    notes: 'Chicago is #2 US industrial market. I-80 corridor has largest concentration of mega-warehouses in US. Cook County assessment is notoriously complex — commercial at 25%, industrial at 33%. Tax appeals are common.',
  },
  IN: {
    name: 'Indiana',
    property_tax_rate: 0.0085,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Indianapolis', 'Fort Wayne', 'Evansville'],
    industrial_hubs: ['Indianapolis (crossroads of America — I-65/I-70/I-69)', 'Plainfield/Whitestown (mega-logistics)'],
    cap_rate_range: [0.055, 0.070],
    key_operators: ['Duke Realty (now Prologis)', 'Scannell Properties', 'Becknell Industrial'],
    notes: 'Indianapolis is a top logistics hub — intersection of I-65/I-70. Duke Realty was HQd here before Prologis acquisition. Low cost of living drives labor availability.',
  },
  IA: {
    name: 'Iowa',
    property_tax_rate: 0.0153,
    assessment_ratio: 0.90,
    income_tax: true,
    markets: ['Des Moines', 'Cedar Rapids', 'Davenport'],
    industrial_hubs: ['Des Moines (distribution)', 'Cedar Rapids (food processing)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: ['STAG Industrial'],
    notes: 'Agricultural processing hub. Data center development growing in Des Moines (Meta, Microsoft).',
  },
  KS: {
    name: 'Kansas',
    property_tax_rate: 0.0141,
    assessment_ratio: 0.25,
    income_tax: true,
    markets: ['Kansas City (KS side)', 'Wichita', 'Overland Park'],
    industrial_hubs: ['KC metro (logistics hub)', 'Wichita (aerospace manufacturing)'],
    cap_rate_range: [0.060, 0.080],
    key_operators: ['NorthPoint Development', 'STAG Industrial'],
    notes: 'Kansas City metro spans KS/MO border. NorthPoint is a major spec developer. Wichita is aerospace capital (Spirit AeroSystems, Textron Aviation).',
  },
  KY: {
    name: 'Kentucky',
    property_tax_rate: 0.0086,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Louisville', 'Lexington', 'Northern Kentucky/Cincinnati metro'],
    industrial_hubs: ['Louisville (UPS Worldport — air cargo capital)', 'Northern KY (Cincinnati airport/Amazon Air Hub)'],
    cap_rate_range: [0.058, 0.075],
    key_operators: ['Prologis', 'Al. Neyer'],
    notes: 'UPS Worldport in Louisville makes it the #3 air cargo hub globally. Amazon Air Hub at CVG. "Bourbon Trail" of warehousing.',
  },
  LA: {
    name: 'Louisiana',
    property_tax_rate: 0.0055,
    assessment_ratio: 0.15,
    income_tax: true,
    markets: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lake Charles'],
    industrial_hubs: ['Port of South Louisiana (bulk cargo)', 'Lake Charles (LNG)', 'Baton Rouge (petrochemical)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: [],
    notes: 'Chemical corridor along Mississippi River. LNG export terminals in Lake Charles/Cameron. Low assessment ratio keeps tax burden manageable.',
  },
  ME: {
    name: 'Maine',
    property_tax_rate: 0.0136,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Portland', 'Bangor'],
    industrial_hubs: ['Portland (last-mile)', 'Scarborough/Westbrook'],
    cap_rate_range: [0.065, 0.085],
    key_operators: ['STAG Industrial'],
    notes: 'Limited industrial market. Portland growing as last-mile hub for northern New England.',
  },
  MD: {
    name: 'Maryland',
    property_tax_rate: 0.0109,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Baltimore', 'Frederick', 'Hagerstown'],
    industrial_hubs: ['Baltimore port area', 'I-81 corridor (Hagerstown)', 'BWI/Anne Arundel (distribution)'],
    cap_rate_range: [0.055, 0.070],
    key_operators: ['Prologis', 'St. John Properties', 'Chesapeake Real Estate Group'],
    notes: 'Port of Baltimore is major auto import port. I-81 corridor connects to PA/WV. Strong federal/defense presence drives some industrial demand.',
  },
  MA: {
    name: 'Massachusetts',
    property_tax_rate: 0.0122,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Boston', 'Worcester', 'Springfield'],
    industrial_hubs: ['Route 128/I-495 (biotech/lab/flex)', 'Worcester (distribution)', 'I-91 corridor'],
    cap_rate_range: [0.050, 0.065],
    key_operators: ['Prologis', 'King Street Properties', 'CBRE Investment'],
    notes: 'Lab/flex space is premium category in Greater Boston. Route 128 corridor is life sciences hub. Extremely tight industrial vacancy.',
  },
  MI: {
    name: 'Michigan',
    property_tax_rate: 0.0154,
    assessment_ratio: 0.50,
    income_tax: true,
    markets: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Kalamazoo'],
    industrial_hubs: ['Detroit metro (auto manufacturing)', 'Grand Rapids (furniture/manufacturing)', 'I-94 corridor'],
    cap_rate_range: [0.060, 0.080],
    key_operators: ['Ashley Capital', 'Hillwood', 'Prologis'],
    notes: 'Auto industry drives industrial demand. EV transition creating new manufacturing facilities. Headlee Amendment caps assessment increases.',
  },
  MN: {
    name: 'Minnesota',
    property_tax_rate: 0.0111,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Minneapolis', 'St. Paul', 'Bloomington', 'Eden Prairie'],
    industrial_hubs: ['Minneapolis I-494/I-694 corridor', 'Shakopee/Prior Lake (e-commerce)', 'Rogers/Otsego'],
    cap_rate_range: [0.055, 0.072],
    key_operators: ['Prologis', 'United Properties', 'Ryan Companies'],
    notes: 'Twin Cities is a strong secondary industrial market. Cold storage demand from food industry (General Mills, Cargill, Target HQ).',
  },
  MS: {
    name: 'Mississippi',
    property_tax_rate: 0.0081,
    assessment_ratio: 0.15,
    income_tax: true,
    markets: ['Jackson', 'Gulfport', 'Tupelo'],
    industrial_hubs: ['Golden Triangle (Columbus — aerospace)', 'Gulfport (port)'],
    cap_rate_range: [0.070, 0.090],
    key_operators: [],
    notes: 'Low cost state for manufacturing. Airbus supplier corridor. Ingalls Shipbuilding in Pascagoula.',
  },
  MO: {
    name: 'Missouri',
    property_tax_rate: 0.0097,
    assessment_ratio: 0.32,
    income_tax: true,
    markets: ['Kansas City (MO side)', 'St. Louis', 'Springfield'],
    industrial_hubs: ['KC metro (logistics crossroads)', 'St. Louis (bi-state industrial)', 'Springfield (distribution)'],
    cap_rate_range: [0.058, 0.075],
    key_operators: ['NorthPoint Development', 'Prologis', 'TriStar Properties'],
    notes: 'KC is a major logistics hub — BNSF intermodal. St. Louis has large legacy industrial stock. Two-state metro complicates tax analysis.',
  },
  MT: {
    name: 'Montana',
    property_tax_rate: 0.0084,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Billings', 'Missoula', 'Great Falls'],
    industrial_hubs: ['Billings (energy/ag distribution)'],
    cap_rate_range: [0.070, 0.090],
    key_operators: [],
    notes: 'Very limited institutional industrial market. Energy and agriculture dominate.',
  },
  NE: {
    name: 'Nebraska',
    property_tax_rate: 0.0173,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Omaha', 'Lincoln'],
    industrial_hubs: ['Omaha (distribution — geographic center of US)'],
    cap_rate_range: [0.060, 0.080],
    key_operators: ['STAG Industrial'],
    notes: 'Omaha is underrated logistics market — central US location. Data center growth (Facebook/Meta). High property taxes.',
  },
  NV: {
    name: 'Nevada',
    property_tax_rate: 0.0055,
    assessment_ratio: 0.35,
    income_tax: false,
    markets: ['Las Vegas', 'Reno/Sparks', 'Henderson', 'North Las Vegas'],
    industrial_hubs: ['North Las Vegas (mega-distribution)', 'Reno/Tahoe-Reno Industrial Center (TRIC)', 'Henderson (last-mile)'],
    cap_rate_range: [0.048, 0.065],
    key_operators: ['Prologis', 'VanTrust', 'Panattoni', 'Dermody Properties'],
    notes: 'No state income tax. TRIC in Reno is largest industrial park in US (107K acres). Tesla Gigafactory. NV has abatement programs for industrial. North Las Vegas is one of hottest industrial markets in US.',
  },
  NH: {
    name: 'New Hampshire',
    property_tax_rate: 0.0186,
    assessment_ratio: 1.0,
    income_tax: false,
    markets: ['Manchester', 'Nashua', 'Concord'],
    industrial_hubs: ['Southern NH (Boston spillover — I-93/Route 3)'],
    cap_rate_range: [0.060, 0.075],
    key_operators: ['STAG Industrial'],
    notes: 'No income or sales tax — but very high property tax. Southern NH benefits from Boston industrial spillover. Limited supply.',
  },
  NJ: {
    name: 'New Jersey',
    property_tax_rate: 0.0249,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Newark/Elizabeth', 'Edison/New Brunswick', 'Exit 8A corridor', 'Meadowlands', 'Camden'],
    industrial_hubs: ['NJ Turnpike Exit 8A (largest East Coast industrial submarket)', 'Port Newark/Elizabeth (container port)', 'Meadowlands (last-mile to NYC)', 'I-78 corridor'],
    cap_rate_range: [0.042, 0.058],
    key_operators: ['Prologis', 'Hartz Mountain', 'Russo Development', 'Matrix Development', 'Bridge Industrial'],
    notes: 'Highest property taxes in US. Exit 8A is the #1 industrial submarket on East Coast. Port Newark is busiest East Coast port. NJ warehouse vacancy <2%. Rents have doubled since 2020. Transit/tolling costs matter for tenant decisions.',
  },
  NM: {
    name: 'New Mexico',
    property_tax_rate: 0.0080,
    assessment_ratio: 0.333,
    income_tax: true,
    markets: ['Albuquerque', 'Santa Fe', 'Las Cruces'],
    industrial_hubs: ['Albuquerque (tech/defense)', 'Santa Teresa (border logistics)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: [],
    notes: 'Santa Teresa border crossing growing as nearshoring/Mexico trade increases. Sandia/Kirtland defense tech.',
  },
  NY: {
    name: 'New York',
    property_tax_rate: 0.0172,
    assessment_ratio: 1.0,  // varies wildly by municipality
    income_tax: true,
    markets: ['NYC (Bronx/Brooklyn/Queens)', 'Long Island', 'Westchester', 'Albany', 'Buffalo', 'Syracuse'],
    industrial_hubs: ['Bronx/South Bronx (last-mile to Manhattan)', 'Brooklyn Navy Yard', 'Long Island (constrained infill)', 'Hudson Valley'],
    cap_rate_range: [0.040, 0.060],
    key_operators: ['Prologis', 'Link Logistics', 'Innovo Property Group', 'Turnbridge Equities'],
    notes: 'NYC industrial is ultra-tight. South Bronx is most expensive last-mile in US. Brooklyn industrial converting to mixed-use at premium. Upstate NY has legacy manufacturing at much higher caps. Assessment varies dramatically by locality.',
  },
  NC: {
    name: 'North Carolina',
    property_tax_rate: 0.0084,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Charlotte', 'Raleigh/Durham', 'Greensboro', 'Winston-Salem'],
    industrial_hubs: ['Charlotte I-85 corridor', 'Triad (Greensboro/Winston-Salem — FedEx hub)', 'Triangle (RTP tech/pharma)'],
    cap_rate_range: [0.052, 0.068],
    key_operators: ['Prologis', 'Beacon Partners', 'Childress Klein', 'Wexford Science'],
    notes: 'Charlotte is top growth market. Piedmont Triad has FedEx mid-Atlantic hub. RTP drives life sciences/lab. Toyota battery plant in Greensboro.',
  },
  ND: {
    name: 'North Dakota',
    property_tax_rate: 0.0098,
    assessment_ratio: 0.50,
    income_tax: true,
    markets: ['Fargo', 'Bismarck', 'Grand Forks'],
    industrial_hubs: ['Fargo (ag/tech distribution)', 'Williston (oil field services)'],
    cap_rate_range: [0.070, 0.090],
    key_operators: [],
    notes: 'Oil production drives western ND industrial. Fargo has small but growing tech sector (Microsoft). Very limited institutional market.',
  },
  OH: {
    name: 'Ohio',
    property_tax_rate: 0.0156,
    assessment_ratio: 0.35,
    income_tax: true,
    markets: ['Columbus', 'Cleveland', 'Cincinnati', 'Dayton'],
    industrial_hubs: ['Columbus (logistics capital of Midwest)', 'I-70/I-71 corridor', 'Cincinnati/NKY (air cargo)', 'Cleveland (manufacturing)'],
    cap_rate_range: [0.055, 0.072],
    key_operators: ['Prologis', 'NorthPoint Development', 'Al. Neyer', 'Duke Realty (now Prologis)', 'Pizzuti Companies'],
    notes: 'Columbus is a top-5 US logistics market. Honda, Intel ($20B fab), Amazon mega-presence. Ohio offers significant tax abatements. Within 600 miles of 60% of US/Canadian population.',
  },
  OK: {
    name: 'Oklahoma',
    property_tax_rate: 0.0090,
    assessment_ratio: 0.11,
    income_tax: true,
    markets: ['Oklahoma City', 'Tulsa'],
    industrial_hubs: ['OKC (energy/distribution)', 'Tulsa (manufacturing/aerospace)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: ['Price Edwards', 'Newmark'],
    notes: 'Low assessment ratio keeps effective tax burden low. Energy sector drives demand. American Airlines and USPS maintenance in Tulsa.',
  },
  OR: {
    name: 'Oregon',
    property_tax_rate: 0.0097,
    assessment_ratio: 1.0,  // Measure 50: assessed at 1995 value + 3%/yr
    income_tax: true,
    markets: ['Portland', 'Salem', 'Eugene', 'Bend'],
    industrial_hubs: ['Portland (port/rail — Columbia corridor)', 'Hillsboro (Intel/semiconductor)', 'Rivergate'],
    cap_rate_range: [0.050, 0.068],
    key_operators: ['Prologis', 'Capstone Partners', 'Specht Development'],
    notes: 'No sales tax (tenant benefit). Measure 50 caps assessed value growth at 3%/yr — major tax advantage for long-held properties. Intel is largest private employer. Portland port handles significant grain/auto cargo.',
  },
  PA: {
    name: 'Pennsylvania',
    property_tax_rate: 0.0153,
    assessment_ratio: 1.0,  // varies by county
    income_tax: true,
    markets: ['Philadelphia', 'Lehigh Valley', 'Harrisburg', 'Pittsburgh'],
    industrial_hubs: ['Lehigh Valley (I-78 corridor — mega distribution)', 'I-81 corridor', 'Philadelphia port', 'Pittsburgh (reshoring manufacturing)'],
    cap_rate_range: [0.052, 0.070],
    key_operators: ['Prologis', 'Liberty Property', 'Hillwood', 'Ashley Capital', 'Stonemont'],
    notes: 'Lehigh Valley/I-78 is one of hottest US industrial markets. Amazon and FedEx mega-presence. KOZ (Keystone Opportunity Zones) offer 10-year tax abatement. I-81 corridor connects to NJ port traffic.',
  },
  RI: {
    name: 'Rhode Island',
    property_tax_rate: 0.0163,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Providence', 'Warwick', 'Cranston'],
    industrial_hubs: ['Providence/Quonset (port/manufacturing)'],
    cap_rate_range: [0.062, 0.078],
    key_operators: ['STAG Industrial'],
    notes: 'Very small market. Quonset Business Park is primary institutional-grade industrial area.',
  },
  SC: {
    name: 'South Carolina',
    property_tax_rate: 0.0057,
    assessment_ratio: 0.06,  // manufacturing gets 10.5%
    income_tax: true,
    markets: ['Charleston', 'Greenville/Spartanburg', 'Columbia'],
    industrial_hubs: ['Charleston (port — Volvo, BMW supplier chain)', 'Upstate/I-85 (automotive manufacturing)', 'Inland Port Greer'],
    cap_rate_range: [0.052, 0.070],
    key_operators: ['Prologis', 'Becknell Industrial', 'Scout Motors'],
    notes: 'SC has lowest assessment ratio for manufacturing (10.5%). Charleston is fastest-growing East Coast port. BMW plant in Spartanburg. Inland Port concept is a model for supply chain. Scout Motors EV plant coming.',
  },
  SD: {
    name: 'South Dakota',
    property_tax_rate: 0.0131,
    assessment_ratio: 0.85,
    income_tax: false,
    markets: ['Sioux Falls', 'Rapid City'],
    industrial_hubs: ['Sioux Falls (distribution/ag processing)'],
    cap_rate_range: [0.065, 0.085],
    key_operators: [],
    notes: 'No state income tax. Sioux Falls is a growing secondary market but limited institutional industrial supply.',
  },
  TN: {
    name: 'Tennessee',
    property_tax_rate: 0.0068,
    assessment_ratio: 0.40,
    income_tax: false,
    markets: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
    industrial_hubs: ['Memphis (FedEx global hub — #1 air cargo)', 'Nashville (distribution/manufacturing)', 'Chattanooga (VW plant)', 'I-24/I-40 corridor'],
    cap_rate_range: [0.050, 0.068],
    key_operators: ['Prologis', 'Hillwood', 'Panattoni', 'Exeter Property Group'],
    notes: 'No state income tax. Memphis is FedEx global superhub — #1 cargo airport in world. Nashville is top growth market. Ford Blue Oval City EV plant near Memphis.',
  },
  TX: {
    name: 'Texas',
    property_tax_rate: 0.0180,
    assessment_ratio: 1.0,
    income_tax: false,
    markets: ['Dallas-Fort Worth', 'Houston', 'San Antonio', 'Austin', 'El Paso'],
    industrial_hubs: ['DFW South (Alliance/I-35W mega-logistics)', 'Houston (port/energy/petrochemical)', 'San Antonio I-35 corridor', 'Austin (tech/flex)', 'El Paso (border/nearshoring)', 'DFW I-20 corridor'],
    cap_rate_range: [0.048, 0.065],
    key_operators: ['Prologis', 'Hillwood (Alliance)', 'Stream Realty', 'Holt Lunsford', 'Crow Holdings', 'Trammell Crow'],
    notes: 'No state income tax but HIGH property taxes (1.8%+ effective). DFW is #1 US industrial market by new construction. Alliance is largest inland port master-planned community. Houston Ship Channel is largest petrochemical complex in US. Chapter 313/Chapter 380 incentive programs. Texas is recapping — watch for reassessment spikes.',
  },
  UT: {
    name: 'Utah',
    property_tax_rate: 0.0063,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Salt Lake City', 'Provo/Orem', 'St. George'],
    industrial_hubs: ['SLC West (I-80 corridor)', 'Northwest Quadrant', 'Davis/Weber County'],
    cap_rate_range: [0.050, 0.067],
    key_operators: ['Prologis', 'Price Real Estate'],
    notes: 'SLC is a growing logistics hub. Crossroads of I-15/I-80. Large spec development in northwest SLC. Facebook/Meta data center in Eagle Mountain.',
  },
  VT: {
    name: 'Vermont',
    property_tax_rate: 0.0188,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Burlington', 'Montpelier'],
    industrial_hubs: ['Burlington/Colchester'],
    cap_rate_range: [0.068, 0.088],
    key_operators: [],
    notes: 'Very limited industrial market. GlobalFoundries semiconductor fab in Essex Junction is largest private employer.',
  },
  VA: {
    name: 'Virginia',
    property_tax_rate: 0.0082,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Northern Virginia', 'Richmond', 'Hampton Roads', 'Virginia Beach'],
    industrial_hubs: ['Northern Virginia (data center capital of the world — Ashburn)', 'Richmond I-95/I-64', 'Port of Virginia (Hampton Roads)'],
    cap_rate_range: [0.050, 0.068],
    key_operators: ['Prologis', 'W. P. Carey', 'QTS Realty (data centers)'],
    notes: 'Ashburn/Loudoun County has 70%+ of world internet traffic flowing through its data centers. Data centers are a unique industrial asset class here. Port of Virginia is deepest port on East Coast (55ft).',
  },
  WA: {
    name: 'Washington',
    property_tax_rate: 0.0093,
    assessment_ratio: 1.0,
    income_tax: false,
    markets: ['Seattle/Tacoma', 'Spokane', 'Vancouver'],
    industrial_hubs: ['Kent Valley (mega-distribution)', 'Port of Tacoma', 'SeaTac area', 'Spokane (inland PNW distribution)'],
    cap_rate_range: [0.045, 0.060],
    key_operators: ['Prologis', 'Dermody Properties', 'LBA Realty'],
    notes: 'No state income tax. Kent Valley is primary Puget Sound industrial market — Amazon HQ2 proximity drives demand. Port of Tacoma handles trans-Pacific cargo. Extremely tight vacancy.',
  },
  WV: {
    name: 'West Virginia',
    property_tax_rate: 0.0058,
    assessment_ratio: 0.60,
    income_tax: true,
    markets: ['Charleston', 'Huntington', 'Morgantown'],
    industrial_hubs: ['I-64 corridor', 'Eastern Panhandle (DC spillover)'],
    cap_rate_range: [0.075, 0.095],
    key_operators: [],
    notes: 'Very limited institutional market. Eastern Panhandle near DC has some growth. Chemical industry legacy along Kanawha Valley.',
  },
  WI: {
    name: 'Wisconsin',
    property_tax_rate: 0.0175,
    assessment_ratio: 1.0,
    income_tax: true,
    markets: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha/Racine'],
    industrial_hubs: ['Milwaukee I-94 corridor', 'Kenosha (Chicago spillover)', 'Foxconn/Mount Pleasant'],
    cap_rate_range: [0.060, 0.078],
    key_operators: ['Prologis', 'Zilber Property Group'],
    notes: 'Milwaukee is a legacy manufacturing market. Kenosha/Racine benefits from Chicago industrial spillover. High property taxes. Foxconn campus (now mostly data center).',
  },
  WY: {
    name: 'Wyoming',
    property_tax_rate: 0.0061,
    assessment_ratio: 0.115,
    income_tax: false,
    markets: ['Cheyenne', 'Casper'],
    industrial_hubs: ['Cheyenne (data centers — low power costs, no income tax)'],
    cap_rate_range: [0.070, 0.090],
    key_operators: ['Microsoft (data centers)'],
    notes: 'No state income tax. Cheyenne is emerging data center market (cheap power, cool climate, tax-friendly). Very limited traditional industrial market.',
  },
};

/**
 * Build state-specific system prompt for the edge model.
 * This is the "area expert" — local knowledge injected into every cook call.
 */
export function stateExpertPrompt(stateCode) {
  const s = STATES[stateCode.toUpperCase()];
  if (!s) return null;

  return `You are a ${s.name} commercial real estate area expert and Intelligence Object structuring engine.

LOCAL MARKET KNOWLEDGE FOR ${s.name.toUpperCase()}:
- Property tax rate: ${(s.property_tax_rate * 100).toFixed(2)}% effective
- Assessment ratio: ${(s.assessment_ratio * 100).toFixed(1)}% of market value
- State income tax: ${s.income_tax ? 'Yes' : 'No state income tax'}
- Cap rate range (industrial): ${(s.cap_rate_range[0] * 100).toFixed(1)}% - ${(s.cap_rate_range[1] * 100).toFixed(1)}%
- Major markets: ${s.markets.join(', ')}
- Industrial hubs: ${s.industrial_hubs.join('; ')}
- Key operators: ${s.key_operators.length ? s.key_operators.join(', ') : 'Limited institutional presence'}
- Local notes: ${s.notes}

RULES:
- Structure raw data into exact JSON Intelligence Object schema.
- ONLY use data provided. Never hallucinate values.
- Apply local knowledge for risk assessment and confidence scoring.
- If cap rate is outside the normal ${(s.cap_rate_range[0] * 100).toFixed(1)}%-${(s.cap_rate_range[1] * 100).toFixed(1)}% range, flag as risk factor.
- Use ${(s.property_tax_rate * 100).toFixed(2)}% property tax rate to estimate if not provided.
- Assessment ratio is ${(s.assessment_ratio * 100).toFixed(1)}% — use to cross-check assessed vs market value.
- All financial values in USD (raw numbers). Cap rates as decimals. SF as integers.
- Return ONLY valid JSON. No explanation. No markdown.`;
}

/**
 * List of all state codes.
 */
export const STATE_CODES = Object.keys(STATES);
