/**
 * Mock Responses — Schema-valid, realistic CRE data
 * ==================================================
 * One mock per skill. Used for:
 * - Offline testing (no AI call)
 * - Client development (predictable output)
 * - Schema validation testing
 */

export const MOCKS = {
  broker_senior: {
    skill: 'broker_senior',
    deal_verdict: 'pursue',
    pricing: {
      value_range: [11200000, 13100000],
      cap_rate: 0.058,
      price_psf: 147,
      basis: 'Comparable sales in Alliance submarket: $140-155/SF for NNN single-tenant industrial. Applied 5.75% cap to $725,000 NOI.',
    },
    risk_assessment: {
      score: 72,
      flags: [
        'Single tenant concentration — 100% income from FedEx Ground',
        'Lease expiry in 7 years — refinance risk at year 5',
        'Tarrant County reassessment pending — potential tax basis increase',
      ],
      mitigants: [
        'FedEx Ground investment-grade credit (BBB)',
        'Alliance submarket vacancy 2.8% — strong re-leasing fundamentals',
        'Below-market rent at $8.50/SF vs market $9.75/SF — built-in reversionary upside',
      ],
    },
    deal_structure: {
      recommended_offer: 12200000,
      hold_period: 7,
      target_irr: 0.14,
      exit_cap: 0.065,
    },
    market_context: {
      submarket: 'Alliance / North Fort Worth',
      vacancy: 0.028,
      rent_trend: 'Positive — 6.2% YoY growth, driven by e-commerce and 3PL expansion along I-35W corridor',
    },
    ic_notes: 'Alliance FedEx Ground — clean single-tenant NNN with investment-grade credit. Below-market rent provides reversionary upside at lease rollover. Main risk is single-tenant exposure, mitigated by sub-3% submarket vacancy. Recommend pursuit at $12.2M ($143/SF, 5.9% cap). Structure as 7-year hold with 65% LTV agency debt.',
  },

  broker_junior: {
    skill: 'broker_junior',
    task_type: 'comp_pull',
    deliverable: {
      comps: [
        { address: '3100 Lehigh St, Allentown, PA', sf: 42000, rent_psf: 8.75, lease_type: 'NNN', date: '2025-09', tenant: 'FedEx Supply Chain' },
        { address: '7200 Industrial Blvd, Macungie, PA', sf: 55000, rent_psf: 9.10, lease_type: 'NNN', date: '2025-07', tenant: 'Amazon' },
        { address: '450 Nestle Way, Breinigsville, PA', sf: 38000, rent_psf: 8.25, lease_type: 'Modified Gross', date: '2025-11', tenant: 'Uline' },
        { address: '2800 Airport Rd, Bethlehem, PA', sf: 48000, rent_psf: 9.50, lease_type: 'NNN', date: '2025-06', tenant: 'DHL' },
        { address: '900 Highlands Blvd, Easton, PA', sf: 41000, rent_psf: 8.60, lease_type: 'NNN', date: '2025-10', tenant: 'XPO Logistics' },
      ],
      summary: 'Lehigh Valley flex/industrial: $8.25-$9.50/SF NNN. 42-55K SF range. Vacancy tight at 3.1%. Strong 3PL and e-commerce tenant demand.',
      market: 'Lehigh Valley / I-78 Corridor',
    },
    next_steps: [
      'Verify lease expiry dates on each comp via CoStar',
      'Pull sale comps for investment-grade pricing benchmarks',
      'Schedule tour of subject and 2 nearest comps',
    ],
    time_estimate: '2-3 hours for full comp package with verification',
  },

  intelligence_query: {
    skill: 'intelligence_query',
    query_interpreted: 'Cold storage properties in Florida with capitalization rates exceeding 5.5%',
    objects_found: 3,
    results: [
      { object_id: 'pio_00a3f7e81b2c', relevance: 0.95, summary: '125,000 SF cold storage in Jacksonville, FL. 5.8% cap, $12.2M value. Tenant: Lineage Logistics.' },
      { object_id: 'pio_00b8c2d94e1a', relevance: 0.88, summary: '85,000 SF freezer/cooler in Lakeland, FL. 6.1% cap, $7.8M value. Multi-tenant.' },
      { object_id: 'pio_00c1a5f03d7e', relevance: 0.82, summary: '200,000 SF cold storage distribution in Hialeah, FL. 5.7% cap, $22.5M value. Tenant: Americold.' },
    ],
    reasoning: 'Filtered sb-intelligence for asset_type=cold_storage, state=FL, cap_rate>0.055. Florida cold storage trades at premium due to perishable import volume through Miami and JAXPORT. 3 objects match criteria out of 47 Florida industrial PIOs.',
    suggested_queries: [
      'Compare Florida cold storage cap rates to Texas cold storage',
      'Show cold storage properties near JAXPORT within 10 miles',
      'What is the average rent/SF for Florida cold storage?',
    ],
  },

  bookmaker: {
    skill: 'bookmaker',
    reason_layer: {
      investment_thesis: 'Last-mile Amazon cross-dock in Savannah, one of the fastest-growing port markets in the US. 10-year NNN lease with investment-grade credit eliminates near-term leasing risk. Below-replacement-cost basis at $62.50/SF. Port of Savannah volume growing 15% YoY positions this asset for long-term demand.',
      financial_summary: {
        noi: 1250000,
        cap_rate: 0.054,
        irr_projection: 0.138,
        price_psf: 115,
        rent_psf: 6.25,
        occupancy: 1.0,
      },
      market_analysis: 'Savannah is the #3 US container port by volume, growing at 15% YoY. South Savannah industrial vacancy is 2.4% with 8.2% rent growth. Amazon has committed to 3 additional facilities in the market. Infrastructure: deepwater berth access, CSX/NS dual rail, I-16/I-95 interchange.',
      risk_factors: [
        'Single tenant exposure (Amazon)',
        'Savannah supply pipeline: 4.2M SF under construction',
        'Hurricane zone — elevated insurance costs',
      ],
      comparable_sales: [
        { address: 'Port Wentworth Logistics Center, GA', sf: 180000, price_psf: 120, cap_rate: 0.052, date: '2025-08' },
        { address: '250 Jimmy DeLoach Pkwy, GA', sf: 225000, price_psf: 108, cap_rate: 0.057, date: '2025-05' },
      ],
    },
    ui_layer: {
      om_title: 'Savannah Cross-Dock — Amazon Last-Mile Distribution',
      executive_summary: 'Institutional-quality 200,000 SF cross-dock in South Savannah, 100% leased to Amazon on a 10-year NNN lease at $6.25/SF. Located 8 miles from the Port of Savannah, the fastest-growing container port in the US. Offered at $23.0M (5.4% cap, $115/SF).',
      sections: [
        {
          heading: 'Investment Highlights',
          content: '- 10-year Amazon NNN lease — zero landlord responsibility\n- Port of Savannah: #3 US container port, 15% YoY volume growth\n- Below-replacement-cost basis: $62.50/SF land + building vs $85/SF+ new construction\n- 2.4% submarket vacancy — structural demand exceeds supply\n- Dual rail access (CSX + Norfolk Southern) within 3 miles',
        },
        {
          heading: 'Property Overview',
          content: '200,000 SF cross-dock distribution facility on 15 acres. 36\' clear height, 80 dock doors (40 per side), ESFR sprinklers, LED lighting, full truck court depth. Built 2019. Concrete tilt-up construction.',
        },
        {
          heading: 'Financial Analysis',
          content: 'NOI: $1,250,000 | Cap Rate: 5.4% | Price: $23,000,000 ($115/SF)\nRent: $6.25/SF NNN with 2.5% annual escalations\nProjected IRR: 13.8% (7-year hold, 6.0% exit cap)\nDebt assumption: 65% LTV, 5.25% fixed, 10-year term',
        },
        {
          heading: 'Market Overview',
          content: 'The Savannah industrial market has emerged as one of the top 5 US logistics markets. Port of Savannah handled 5.8M TEUs in 2025, with the Mason Mega Rail Terminal doubling intermodal capacity. South Savannah vacancy: 2.4%. Average asking rent: $6.50/SF NNN (+8.2% YoY).',
        },
        {
          heading: 'Risk Factors',
          content: '1. Single-tenant concentration: 100% income from Amazon\n2. Supply pipeline: 4.2M SF under construction in greater Savannah\n3. Hurricane exposure: Chatham County flood zone considerations\n\nMitigants: Amazon investment-grade credit (AA-), NNN structure transfers operating risk, sub-3% vacancy provides re-leasing backstop.',
        },
      ],
      format: 'markdown',
    },
  },

  deal_tracker: {
    skill: 'deal_tracker',
    action: 'update',
    deal: {
      deal_id: 'DEAL-TX-001',
      property: '8500 Alliance Gateway, Fort Worth, TX — 85,000 SF FedEx Ground',
      stage: 'loi',
      milestones: [
        { name: 'Site tour', due: '2026-02-10', status: 'done' },
        { name: 'LOI submission', due: '2026-02-18', status: 'done' },
        { name: 'LOI acceptance', due: '2026-02-25', status: 'done' },
        { name: 'PSA execution', due: '2026-03-15', status: 'pending' },
        { name: 'Phase I ESA', due: '2026-03-20', status: 'pending' },
        { name: 'Inspection deadline', due: '2026-04-14', status: 'pending' },
        { name: 'Financing commitment', due: '2026-04-25', status: 'pending' },
        { name: 'Close', due: '2026-05-15', status: 'pending' },
      ],
      key_dates: {
        loi_submitted: '2026-02-18',
        psa_executed: null,
        inspection_deadline: '2026-04-14',
        close_date: '2026-05-15',
      },
      next_action: 'Execute PSA by March 15. Engage Phase I vendor. Confirm lender term sheet.',
      days_in_stage: 7,
    },
    pipeline_summary: {
      active_deals: 4,
      total_value: 52700000,
      overdue_items: [],
    },
  },

  developer: {
    skill: 'developer',
    task_type: 'code_gen',
    deliverable: {
      code: `# Cook 10 TX warehouses through state expert
for i in $(seq 1 10); do
  curl -s -X POST https://router.swarmandbee.com/cook/TX \\
    -H "Content-Type: application/json" \\
    -d '{
      "data": {
        "address": "'"$i"'00 Alliance Blvd, Fort Worth, TX",
        "sf": '"$((RANDOM % 100000 + 50000))"',
        "asset_type": "warehouse",
        "clear_height": 32,
        "year_built": '"$((RANDOM % 10 + 2015))"'
      },
      "context": "Industrial warehouse in Alliance corridor"
    }' | jq '.cooked, .object.object_id'
  sleep 1
done`,
      language: 'bash',
      files_affected: [],
      dependencies: ['curl', 'jq'],
    },
    validation: {
      syntax_valid: true,
      tests_suggested: [
        'Run with --dry-run flag first to verify endpoint connectivity',
        'Check each response for cooked:true',
        'Verify objects appear in GET /states/TX/feed after batch',
      ],
    },
    notes: 'Uses state expert endpoint POST /cook/TX which injects Texas area knowledge (no income tax, Alliance submarket, Tarrant County tax rates). Each cook costs ~$0.0002 via Qwen3-30B-A3B on Cloudflare edge.',
  },

  signal_scraper: {
    skill: 'signal_scraper',
    events_detected: 3,
    events: [
      {
        event_type: 'just_listed',
        confidence: 0.94,
        property: '45,000 SF flex industrial — 1200 Commerce Dr, Lehigh Valley, PA',
        source: 'CBRE listing alert',
        broker: 'Mike Johnson, CBRE Allentown',
        asking_price: 8500000,
        key_terms: 'NNN, 92% occupied, 2 suites available',
        detected_at: '2026-02-25T14:30:00Z',
      },
      {
        event_type: 'just_sold',
        confidence: 0.91,
        property: '120,000 SF warehouse — 5600 Distribution Way, Savannah, GA',
        source: 'CoStar press release',
        broker: 'Sarah Chen, JLL Atlanta',
        sale_price: 14200000,
        cap_rate: 0.055,
        buyer: 'Prologis',
        detected_at: '2026-02-25T10:15:00Z',
      },
      {
        event_type: 'under_contract',
        confidence: 0.87,
        property: '85,000 SF cross-dock — Alliance Gateway, Fort Worth, TX',
        source: 'LinkedIn post by listing broker',
        broker: 'David Park, Cushman & Wakefield',
        contract_price: null,
        key_terms: 'Went under contract in 12 days, multiple offers',
        detected_at: '2026-02-24T16:45:00Z',
      },
    ],
    raw_signals_processed: 47,
    signal_to_event_ratio: 0.064,
    sources_scanned: ['CBRE listings', 'JLL press releases', 'CoStar alerts', 'LinkedIn broker posts', 'Cushman & Wakefield market reports'],
  },

  investor: {
    skill: 'investor',
    mode: 'match',
    property_summary: '85,000 SF single-tenant NNN warehouse in Alliance, TX. FedEx Ground, 7yr remaining, $8.50/SF. Asking $12.5M.',
    matches: [
      {
        buyer_type: 'exchange_1031',
        probability: 0.85,
        pricing_expectation: { cap_rate: 0.058, price_psf: 147, total_value: 12500000 },
        rationale: 'Classic 1031 target: single-tenant NNN with investment-grade credit, clean cash flow, $12.5M price point fits $5M-$25M exchange range. FedEx Ground credit satisfies lender requirements. 7-year remaining term provides adequate hold period.',
        example_buyers: ['Private 1031 exchangers via Marcus & Millichap', 'Inland Private Capital Group', 'ExchangeRight'],
      },
      {
        buyer_type: 'reit',
        probability: 0.70,
        pricing_expectation: { cap_rate: 0.055, price_psf: 152, total_value: 12920000 },
        rationale: 'STAG Industrial and FR (First Industrial) are programmatic buyers of single-tenant industrial in DFW. Accretive to AFFO at sub-6% cap. Alliance is core submarket for REIT portfolios.',
        example_buyers: ['STAG Industrial', 'First Industrial (FR)', 'Terreno Realty'],
      },
      {
        buyer_type: 'private_capital',
        probability: 0.60,
        pricing_expectation: { cap_rate: 0.060, price_psf: 140, total_value: 11900000 },
        rationale: 'DFW family offices and HNW investors target credit-tenant NNN as bond-like cash flow. $12.5M fits single-check writes. Local operators know Alliance fundamentals.',
        example_buyers: ['Dallas family offices', 'Local HNW via Lee & Associates', 'Mohr Capital'],
      },
      {
        buyer_type: 'institutional',
        probability: 0.25,
        pricing_expectation: { cap_rate: 0.050, price_psf: 165, total_value: 14025000 },
        rationale: 'Below typical institutional minimum ($25M+) but could fit a programmatic small-bay strategy. Prologis/Blackstone unlikely at this size. More likely as part of a portfolio aggregation.',
        example_buyers: ['Prologis (portfolio only)', 'GLP', 'Brookfield (via fund)'],
      },
    ],
    capital_stack: {
      equity_required: 4375000,
      debt_available: 8125000,
      ltv: 0.65,
      debt_rate: 0.0525,
      equity_multiple: 1.85,
    },
    market_depth: {
      buyer_pool_size: 'deep',
      expected_offers: 8,
      marketing_period_days: 45,
      competitive_tension: 'high',
    },
    recommendation: 'Price at $12.5M (5.8% cap). Target 1031 and REIT buyers simultaneously. 1031 exchangers will pay closest to ask due to tax motivation. REITs may push sub-5.5% cap. Expect 6-10 offers in 30-45 day marketing period. Alliance NNN with FedEx credit is a highly liquid product.',
  },

  exchange_1031: {
    skill: 'exchange_1031',
    mode: 'boot_calc',
    qualification: {
      qualifies: true,
      like_kind: true,
      held_for_investment: true,
      issues: [],
      recommendation: 'Property qualifies for 1031 exchange. Held for investment, like-kind real property to real property. No dealer/flip concerns.',
    },
    relinquished: {
      property: '45,000 SF flex industrial, Lehigh Valley, PA',
      sale_price: 8500000,
      adjusted_basis: 4200000,
      debt_payoff: 3100000,
      closing_costs: 425000,
      net_proceeds: 4975000,
      gain: 4300000,
      depreciation_recapture: 1800000,
    },
    timeline: {
      sale_close: '2026-03-01',
      id_deadline_45: '2026-04-15',
      exchange_deadline_180: '2026-08-28',
      tax_filing_deadline: '2026-10-15',
      days_remaining_id: 49,
      days_remaining_exchange: 184,
      urgency: 'green',
    },
    boot_analysis: {
      cash_boot: 0,
      mortgage_boot: 0,
      total_boot: 0,
      tax_rate_federal: 0.20,
      tax_rate_state: 0.0307,
      depreciation_recapture_rate: 0.25,
      estimated_tax_liability: 0,
      tax_savings_if_exchanged: 1460700,
    },
    replacement_targets: {
      rule_used: '3_property',
      min_value: 8500000,
      min_debt: 3100000,
      targets: [
        {
          description: '85,000 SF NNN warehouse in Alliance, TX. FedEx Ground. 7yr remaining.',
          value: 12500000,
          cap_rate: 0.058,
          why_fits: 'Exceeds min value ($12.5M > $8.5M), NNN structure eliminates management burden, FedEx credit satisfies lender. TX has no state income tax — additional tax efficiency.',
        },
        {
          description: '120,000 SF distribution center in Savannah, GA. XPO Logistics. 10yr NNN.',
          value: 15200000,
          cap_rate: 0.054,
          why_fits: 'Port market growth, long-term lease. Exceeds minimum. New debt of $9.9M exceeds $3.1M minimum debt replacement — zero mortgage boot.',
        },
        {
          description: '60,000 SF cold storage in Jacksonville, FL. Lineage Logistics. 8yr NNN.',
          value: 9800000,
          cap_rate: 0.061,
          why_fits: 'Cold storage premium cap rate. Exceeds minimum value. FL has no state income tax. Niche asset class with limited supply.',
        },
      ],
    },
    risks: [
      'If replacement closes after Aug 28, 2026 — taxable event on full $4.3M gain',
      'If replacement value < $8.5M — cash boot on the difference',
      'If replacement debt < $3.1M — mortgage boot on the difference',
      'Constructive receipt: exchanger must NOT touch proceeds. QI holds all funds.',
    ],
    recommendation: 'Full tax deferral achievable. $1.46M in tax savings at stake. Recommend Target #1 (Alliance TX FedEx) as primary — clean NNN, exceeds all minimums, TX no income tax. ID all 3 targets using 3-property rule by April 15. Engage QI immediately. Do NOT take possession of any sale proceeds.',
  },

  market_report: {
    skill: 'market_report',
    submarket: 'DFW Alliance / North Fort Worth',
    metro: 'Dallas-Fort Worth',
    report_period: 'Q4 2025',
    snapshot: {
      vacancy_rate: 0.032,
      avg_asking_rent_psf: 6.75,
      rent_growth_yoy: 0.074,
      avg_cap_rate: 0.055,
      inventory_sf: 62400000,
      under_construction_sf: 4800000,
      net_absorption_sf: 1850000,
      deliveries_sf: 2100000,
    },
    trends: {
      rent_direction: 'increasing',
      vacancy_direction: 'stable',
      cap_rate_direction: 'compressing',
      demand_drivers: [
        'E-commerce last-mile expansion along I-35W corridor',
        '3PL consolidation — Geodis, XPO, and FedEx all expanding footprint',
        'Port-to-inland intermodal volume increase via BNSF Alliance intermodal facility',
        'Population growth: DFW added 152,000 residents in 2025',
      ],
      supply_risks: [
        '4.8M SF under construction — largest pipeline since 2022',
        'Three speculative buildings over 500K SF delivering Q1 2026',
        'Land costs rising 12% YoY — constraining new starts',
      ],
    },
    notable_transactions: [
      {
        type: 'sale',
        property: 'Alliance Logistics Center — 325,000 SF',
        price: 48750000,
        price_psf: 150,
        cap_rate: 0.052,
        buyer: 'Prologis',
        date: '2025-11',
      },
      {
        type: 'lease',
        property: 'Hillwood Trade Center 4 — 180,000 SF',
        tenant: 'Amazon',
        rent_psf: 7.10,
        term_years: 10,
        lease_type: 'NNN',
        date: '2025-10',
      },
      {
        type: 'sale',
        property: 'Eagle Parkway Distribution — 95,000 SF',
        price: 13300000,
        price_psf: 140,
        cap_rate: 0.057,
        buyer: 'STAG Industrial',
        date: '2025-12',
      },
    ],
    forecast: {
      vacancy_eoy_2026: 0.038,
      rent_growth_2026: 0.055,
      outlook: 'Positive. Alliance remains a top-tier DFW submarket driven by intermodal connectivity and blue-chip tenant demand. Construction pipeline will push vacancy slightly higher in H1 2026 but pre-leasing at 62% suggests absorption will keep pace. Expect 5-6% rent growth and continued cap rate compression for credit-tenant product.',
    },
    sources: ['CoStar Analytics Q4 2025', 'CBRE MarketView DFW Industrial Q4 2025', 'Hillwood Alliance market report', 'Cushman & Wakefield MarketBeat Q4 2025'],
  },

  lead_scorer: {
    skill: 'lead_scorer',
    lead: {
      name: 'Robert Chen',
      company: 'Chen Family Holdings LLC',
      title: 'Managing Principal',
      email: 'rchen@chenfamilyholdings.com',
      phone: '(214) 555-0187',
      source: 'Marcus & Millichap referral',
      first_contact: '2026-02-20',
    },
    score: 87,
    tier: 'hot',
    signals: {
      motivation: {
        score: 95,
        detail: 'Active 1031 exchange — sold 40,000 SF retail center in Plano, TX on Feb 10. 45-day ID deadline April 1. $6.2M net proceeds. Must deploy or face $1.1M tax hit.',
      },
      financial_capacity: {
        score: 90,
        detail: 'Net proceeds of $6.2M with pre-approved debt at 65% LTV. Can target up to $17.7M replacement property. Lender pre-qual letter from Truist on file.',
      },
      timeline_urgency: {
        score: 92,
        detail: 'ID deadline in 35 days (April 1, 2026). Exchange deadline July 9, 2026. Clock is ticking — high motivation to transact quickly.',
      },
      market_fit: {
        score: 82,
        detail: 'Seeking NNN industrial in DFW metro. Current inventory aligns: Alliance FedEx (85K SF, $12.5M), Irving Amazon (62K SF, $9.8M). Both fit 1031 parameters.',
      },
      engagement: {
        score: 78,
        detail: 'Responded to initial outreach within 2 hours. Requested full OM and financials on Alliance FedEx. Scheduled site tour for Feb 28.',
      },
    },
    recommended_action: {
      priority: 'immediate',
      action: 'Send Alliance FedEx OM and financials today. Confirm site tour Feb 28. Prepare 1031 exchange timeline showing ID deadline alignment. CC qualified intermediary on all correspondence.',
      follow_up_date: '2026-02-26',
      assigned_to: 'Senior Broker',
    },
    comparable_leads: {
      avg_score_to_close: 72,
      conversion_rate_at_score: 0.68,
      avg_days_to_close: 38,
    },
  },

  email_composer: {
    skill: 'email_composer',
    email_type: 'cold_outreach',
    tone: 'professional',
    recipient: {
      name: 'Robert Chen',
      company: 'Chen Family Holdings LLC',
      title: 'Managing Principal',
      context: '1031 exchange buyer — $6.2M proceeds, seeking NNN industrial in DFW',
    },
    subject_line: 'Alliance NNN Industrial — Fits Your 1031 Timeline',
    body: `Robert,

I understand you recently closed on your Plano retail center and are identifying replacement properties for your 1031 exchange. I wanted to bring an off-market opportunity to your attention that aligns well with your parameters.

We're representing an 85,000 SF single-tenant NNN warehouse in the Alliance submarket of Fort Worth, fully leased to FedEx Ground with 7 years remaining on a NNN basis at $8.50/SF. The property is offered at $12.5M (5.8% cap, $147/SF).

A few highlights that may resonate:
- Investment-grade tenant (FedEx, BBB-rated) — satisfies exchange lender requirements
- NNN structure with 2.5% annual escalations — zero landlord management
- Alliance submarket vacancy at 2.8% — strong re-leasing fundamentals at rollover
- Texas — no state income tax, additional efficiency for your exchange

Given your April 1 identification deadline, I'd welcome the chance to walk you through the financials and arrange a site visit at your convenience. I have a full OM and rent roll ready to send.

Would Thursday or Friday this week work for a 15-minute call?

Best regards`,
    follow_up_sequence: [
      {
        touch: 1,
        channel: 'email',
        timing: 'Day 0 — Initial outreach (above)',
        subject: 'Alliance NNN Industrial — Fits Your 1031 Timeline',
        purpose: 'Introduce opportunity, establish relevance to 1031 deadline',
      },
      {
        touch: 2,
        channel: 'email',
        timing: 'Day 3 — Follow-up if no reply',
        subject: 'RE: Alliance NNN Industrial — Quick Update',
        purpose: 'Add value: attach 1-page deal summary PDF, mention comparable sale at $150/SF to create urgency',
      },
      {
        touch: 3,
        channel: 'phone',
        timing: 'Day 5 — Phone call',
        subject: null,
        purpose: 'Direct call to discuss opportunity. Reference emails sent. Offer to coordinate with QI. Emphasize ticking ID deadline.',
      },
    ],
    personalization_notes: [
      'Referenced specific Plano retail sale to demonstrate research',
      'Highlighted NNN structure — aligns with passive exchange buyer profile',
      'Emphasized April 1 deadline — creates urgency without being pushy',
      'Texas no-income-tax angle adds exchange-specific value',
    ],
    compliance: {
      canned_spam_compliant: true,
      opt_out_included: false,
      disclaimer_needed: 'Add standard brokerage disclaimer and license number to signature block',
    },
  },

  comp_analyzer: {
    skill: 'comp_analyzer',
    subject_property: {
      address: '8500 Alliance Gateway Blvd, Fort Worth, TX 76177',
      sf: 85000,
      asset_type: 'warehouse',
      year_built: 2018,
      clear_height: 32,
      tenant: 'FedEx Ground',
      lease_type: 'NNN',
      rent_psf: 8.50,
      noi: 722500,
    },
    comparables: [
      {
        address: '9200 Eagle Parkway, Fort Worth, TX 76177',
        sf: 95000,
        sale_date: '2025-12',
        sale_price: 13300000,
        price_psf: 140,
        cap_rate: 0.057,
        year_built: 2017,
        clear_height: 32,
        tenant: 'XPO Logistics',
        lease_type: 'NNN',
        adjustments: {
          size: 0.02,
          age: -0.01,
          location: 0.0,
          tenant_credit: 0.03,
          lease_term: 0.01,
          net_adjustment: 0.05,
          adjusted_price_psf: 147,
        },
      },
      {
        address: '3100 Westport Parkway, Fort Worth, TX 76177',
        sf: 120000,
        sale_date: '2025-11',
        sale_price: 18000000,
        price_psf: 150,
        cap_rate: 0.052,
        year_built: 2019,
        clear_height: 36,
        tenant: 'Amazon',
        lease_type: 'NNN',
        adjustments: {
          size: 0.04,
          age: 0.01,
          location: 0.0,
          tenant_credit: 0.0,
          lease_term: -0.02,
          net_adjustment: 0.03,
          adjusted_price_psf: 154.50,
        },
      },
      {
        address: '6700 Alliance Blvd, Fort Worth, TX 76177',
        sf: 78000,
        sale_date: '2025-09',
        sale_price: 10920000,
        price_psf: 140,
        cap_rate: 0.059,
        year_built: 2016,
        clear_height: 30,
        tenant: 'DHL Supply Chain',
        lease_type: 'NNN',
        adjustments: {
          size: -0.01,
          age: -0.02,
          location: 0.01,
          tenant_credit: 0.02,
          lease_term: 0.02,
          net_adjustment: 0.02,
          adjusted_price_psf: 142.80,
        },
      },
      {
        address: '1400 Intermodal Parkway, Haslet, TX 76052',
        sf: 105000,
        sale_date: '2025-08',
        sale_price: 14700000,
        price_psf: 140,
        cap_rate: 0.056,
        year_built: 2020,
        clear_height: 36,
        tenant: 'UPS Supply Chain Solutions',
        lease_type: 'NNN',
        adjustments: {
          size: 0.03,
          age: 0.02,
          location: -0.01,
          tenant_credit: 0.01,
          lease_term: -0.01,
          net_adjustment: 0.04,
          adjusted_price_psf: 145.60,
        },
      },
    ],
    analysis: {
      unadjusted_range_psf: [140, 150],
      adjusted_range_psf: [142.80, 154.50],
      indicated_value_range: [12138000, 13132500],
      weighted_avg_psf: 147.48,
      weighted_avg_value: 12535800,
      cap_rate_range: [0.052, 0.059],
      implied_cap_rate: 0.057,
    },
    methodology: 'Sales comparison approach using 4 NNN industrial sales within Alliance/North Fort Worth submarket closed within 6 months. Adjustments applied for size differential, age/condition, location, tenant credit quality, and remaining lease term. FedEx Ground credit (BBB) commands 2-3% premium over non-IG tenants. Subject benefits from below-market rent ($8.50 vs market $9.75) providing reversionary upside not captured in direct cap.',
    confidence: 0.88,
    recommendation: 'Indicated value range: $12.1M-$13.5M ($143-$155/SF). Most probable value: $12.5M ($147/SF) at 5.7% cap. The lower end reflects DHL comp with inferior clear height; upper end reflects Amazon comp with superior tenant credit and newer vintage. Subject is well-positioned in the middle of the range given FedEx IG credit and below-market rent.',
  },

  rent_roll_analyzer: {
    skill: 'rent_roll_analyzer',
    property: {
      address: '2400 Commerce Park Drive, Irving, TX 75063',
      asset_type: 'flex_industrial',
      total_sf: 62000,
      year_built: 2015,
      units: 8,
    },
    tenants: [
      {
        suite: '100',
        tenant: 'Precision CNC Machining LLC',
        sf: 18000,
        pct_of_total: 0.290,
        rent_psf: 10.25,
        annual_rent: 184500,
        lease_start: '2023-06-01',
        lease_expiry: '2028-05-31',
        remaining_years: 2.3,
        escalation: 0.03,
        lease_type: 'NNN',
        credit: 'local',
        options: '1x5yr renewal at market',
      },
      {
        suite: '200',
        tenant: 'DFW Medical Supplies Inc',
        sf: 14000,
        pct_of_total: 0.226,
        rent_psf: 11.00,
        annual_rent: 154000,
        lease_start: '2024-01-01',
        lease_expiry: '2031-12-31',
        remaining_years: 5.8,
        escalation: 0.025,
        lease_type: 'NNN',
        credit: 'regional',
        options: '2x5yr renewal at 95% market',
      },
      {
        suite: '300',
        tenant: 'SkyBridge Logistics Corp',
        sf: 12000,
        pct_of_total: 0.194,
        rent_psf: 9.75,
        annual_rent: 117000,
        lease_start: '2022-03-01',
        lease_expiry: '2027-02-28',
        remaining_years: 1.0,
        escalation: 0.025,
        lease_type: 'Modified Gross',
        credit: 'local',
        options: 'None',
      },
      {
        suite: '400',
        tenant: 'Lone Star Electrical Contractors',
        sf: 9500,
        pct_of_total: 0.153,
        rent_psf: 10.50,
        annual_rent: 99750,
        lease_start: '2025-01-01',
        lease_expiry: '2032-12-31',
        remaining_years: 6.8,
        escalation: 0.03,
        lease_type: 'NNN',
        credit: 'local',
        options: '1x3yr renewal at market',
      },
      {
        suite: '500',
        tenant: 'Allied Testing & Inspection',
        sf: 3500,
        pct_of_total: 0.056,
        rent_psf: 12.00,
        annual_rent: 42000,
        lease_start: '2024-07-01',
        lease_expiry: '2029-06-30',
        remaining_years: 3.3,
        escalation: 0.025,
        lease_type: 'NNN',
        credit: 'local',
        options: 'None',
      },
    ],
    vacancy: {
      vacant_suites: ['600', '700', '800'],
      vacant_sf: 5000,
      vacancy_rate: 0.081,
      market_rent_psf: 11.50,
      estimated_downtime_months: 4,
      leasing_cost_psf: 3.50,
    },
    summary: {
      occupied_sf: 57000,
      occupancy_rate: 0.919,
      total_annual_rent: 597250,
      effective_gross_income: 640000,
      weighted_avg_rent_psf: 10.48,
      walt_years: 4.2,
      largest_tenant_pct: 0.290,
    },
    rollover_analysis: {
      year_2026: { sf_expiring: 0, pct_of_total: 0.0, tenants: [] },
      year_2027: { sf_expiring: 12000, pct_of_total: 0.194, tenants: ['SkyBridge Logistics Corp'] },
      year_2028: { sf_expiring: 18000, pct_of_total: 0.290, tenants: ['Precision CNC Machining LLC'] },
      year_2029: { sf_expiring: 3500, pct_of_total: 0.056, tenants: ['Allied Testing & Inspection'] },
      year_2030: { sf_expiring: 0, pct_of_total: 0.0, tenants: [] },
      year_2031: { sf_expiring: 14000, pct_of_total: 0.226, tenants: ['DFW Medical Supplies Inc'] },
      year_2032: { sf_expiring: 9500, pct_of_total: 0.153, tenants: ['Lone Star Electrical Contractors'] },
      peak_rollover_year: 2028,
      peak_rollover_pct: 0.290,
    },
    risk_flags: [
      'SkyBridge Logistics (19.4% of rent) expires Feb 2027 with no renewal options — near-term re-leasing risk',
      'Suite 300 (SkyBridge) on Modified Gross — landlord bears expense risk. Convert to NNN at renewal.',
      '48.4% of occupied SF rolls in 2027-2028 — concentrated rollover window',
      'No tenants are investment-grade credit — all local/regional operators',
      '3 vacant suites (8.1%) — 4-month estimated downtime adds $19,167 in carry costs',
    ],
    recommendations: [
      'Priority 1: Engage SkyBridge now on early renewal — offer 6-month free rent on 5-year NNN extension to lock term and convert from Modified Gross',
      'Priority 2: Lease suites 600-800 (5,000 SF) — market at $11.50/SF NNN, target Q2 2026 occupancy',
      'Priority 3: Begin Precision CNC renewal discussions 12 months before May 2028 expiry — largest tenant at 29%',
      'Mark-to-market opportunity: in-place avg $10.48/SF vs market $11.50/SF — 9.7% upside at rollover',
    ],
  },

  debt_analyzer: {
    skill: 'debt_analyzer',
    property: {
      address: '8500 Alliance Gateway Blvd, Fort Worth, TX 76177',
      asset_type: 'warehouse',
      sf: 85000,
      noi: 722500,
      value: 12500000,
      tenant: 'FedEx Ground',
      lease_type: 'NNN',
      remaining_term_years: 7,
    },
    sizing: {
      max_ltv: 0.65,
      max_loan_amount: 8125000,
      dscr: 1.45,
      dscr_constrained_loan: 8500000,
      binding_constraint: 'ltv',
      recommended_loan: 8125000,
      equity_required: 4375000,
    },
    lender_matches: [
      {
        lender: 'Truist Bank',
        product: 'Fixed-rate term loan',
        rate: 0.0525,
        rate_type: 'fixed',
        term_years: 10,
        amortization_years: 25,
        max_ltv: 0.65,
        min_dscr: 1.25,
        prepayment: 'Yield maintenance year 1-7, 1% year 8-9, open year 10',
        estimated_closing_days: 45,
        fees: 'Origination 0.75%, legal $15K, appraisal $5K',
        pros: ['Competitive rate for IG tenant', 'Flexible prepayment in later years', 'Portfolio lender — faster decisions'],
        cons: ['Yield maintenance restricts early exit', 'Recourse for first 3 years'],
      },
      {
        lender: 'Freddie Mac (via CBRE Capital Markets)',
        product: 'SBL Small Balance Loan',
        rate: 0.0495,
        rate_type: 'fixed',
        term_years: 10,
        amortization_years: 30,
        max_ltv: 0.70,
        min_dscr: 1.20,
        prepayment: 'Defeasance',
        estimated_closing_days: 60,
        fees: 'Origination 1.0%, legal $18K, appraisal $5K, rate lock $12K',
        pros: ['Lowest rate — agency execution', '30-year amortization maximizes cash flow', 'Non-recourse from day 1'],
        cons: ['Defeasance costly if early exit needed', 'Longer closing timeline (60 days)', 'Requires Phase I ESA and seismic'],
      },
      {
        lender: 'JPMorgan Chase',
        product: 'CMBS conduit',
        rate: 0.0545,
        rate_type: 'fixed',
        term_years: 10,
        amortization_years: 30,
        max_ltv: 0.70,
        min_dscr: 1.20,
        prepayment: 'Defeasance or yield maintenance',
        estimated_closing_days: 55,
        fees: 'Origination 0.50%, legal $20K, appraisal $5K, B-piece fee $25K',
        pros: ['Non-recourse', 'Higher max LTV (70%)', 'Standardized CMBS documentation'],
        cons: ['Highest rate of three options', 'B-piece buyer approval required', 'Inflexible post-closing — CMBS servicer'],
      },
    ],
    rate_sensitivity: [
      { rate: 0.0450, annual_debt_service: 489600, dscr: 1.48, monthly_payment: 40800 },
      { rate: 0.0475, annual_debt_service: 502200, dscr: 1.44, monthly_payment: 41850 },
      { rate: 0.0500, annual_debt_service: 515100, dscr: 1.40, monthly_payment: 42925 },
      { rate: 0.0525, annual_debt_service: 528300, dscr: 1.37, monthly_payment: 44025 },
      { rate: 0.0550, annual_debt_service: 541800, dscr: 1.33, monthly_payment: 45150 },
      { rate: 0.0575, annual_debt_service: 555500, dscr: 1.30, monthly_payment: 46292 },
      { rate: 0.0600, annual_debt_service: 569400, dscr: 1.27, monthly_payment: 47450 },
    ],
    cash_flow_impact: {
      noi: 722500,
      debt_service_at_recommended: 528300,
      cash_after_debt: 194200,
      cash_on_cash_return: 0.0444,
      breakeven_occupancy: 0.73,
    },
    recommendation: 'Recommend Freddie Mac SBL via CBRE Capital Markets. Best rate (4.95%), 30-year amortization maximizes levered cash flow, and non-recourse from day 1 protects guarantor. 60-day closing timeline fits PSA execution by March 15 with May 15 close target. FedEx IG credit and Alliance submarket will underwrite cleanly. Submit loan application immediately upon PSA execution. Budget $40K in total closing costs.',
  },

  tax_assessor: {
    skill: 'tax_assessor',
    property: {
      address: '14200 Eastex Freeway, Houston, TX 77032',
      county: 'Harris County',
      state: 'TX',
      asset_type: 'industrial_warehouse',
      sf: 110000,
      year_built: 2014,
      acreage: 8.5,
      tax_account: '1052340001012',
    },
    current_assessment: {
      tax_year: 2025,
      appraised_value: 10780000,
      assessed_value: 10780000,
      land_value: 3400000,
      improvement_value: 7380000,
      tax_rate_per_100: 2.31,
      annual_tax: 249018,
      effective_tax_rate: 0.0231,
    },
    market_analysis: {
      estimated_market_value: 9500000,
      cap_rate_applied: 0.062,
      noi_estimated: 589000,
      comparable_sales_psf: [82, 88, 91, 85],
      avg_comparable_psf: 86.50,
      subject_assessed_psf: 98.0,
      overassessment_pct: 0.12,
      overassessment_dollars: 1280000,
    },
    appeal_recommendation: {
      should_appeal: true,
      confidence: 0.85,
      target_value: 9500000,
      potential_tax_savings: 29568,
      annual_savings: 29568,
      five_year_savings: 147840,
      appeal_deadline: '2026-05-15',
      filing_fee: 0,
      estimated_legal_cost: 7500,
      net_year_one_savings: 22068,
      roi_on_appeal: 2.94,
    },
    supporting_evidence: {
      comparable_sales: [
        { address: '9800 East Freeway, Houston, TX', sf: 95000, sale_date: '2025-10', sale_price: 7790000, price_psf: 82 },
        { address: '5200 Beaumont Hwy, Houston, TX', sf: 125000, sale_date: '2025-08', sale_price: 11000000, price_psf: 88 },
        { address: '3400 Aldine Bender Rd, Houston, TX', sf: 100000, sale_date: '2025-11', sale_price: 9100000, price_psf: 91 },
        { address: '11600 Tanner Rd, Houston, TX', sf: 115000, sale_date: '2025-07', sale_price: 9775000, price_psf: 85 },
      ],
      income_approach: {
        noi: 589000,
        cap_rate: 0.062,
        indicated_value: 9500000,
      },
      equity_comparisons: [
        { address: '9800 East Freeway (similar age, size)', assessed_psf: 84, subject_psf: 98, variance: 0.167 },
        { address: '5200 Beaumont Hwy (similar condition)', assessed_psf: 87, subject_psf: 98, variance: 0.126 },
      ],
    },
    process: {
      jurisdiction: 'Harris County Appraisal District (HCAD)',
      step_1: 'File protest online via iFile (hcad.org) before May 15, 2026',
      step_2: 'Attend informal hearing with appraiser — present comp sales and income approach',
      step_3: 'If informal fails, proceed to Appraisal Review Board (ARB) formal hearing',
      step_4: 'If ARB fails, binding arbitration or district court (properties under $5M assessed)',
      typical_timeline: '60-120 days from filing to resolution',
      success_rate_informal: 0.72,
      success_rate_arb: 0.58,
    },
    recommendation: 'Appeal recommended. Subject is over-assessed by approximately 12% ($1.28M) versus comparable sales and income approach. Harris County has been aggressive on industrial reassessments since 2023. File protest by May 15. Target $9.5M assessed value using sales comparison ($86.50/SF avg) and income approach ($589K NOI / 6.2% cap). Expected annual savings of $29,568. Engage a property tax consultant on contingency (30-35% of savings) to maximize outcome.',
  },

  site_selector: {
    skill: 'site_selector',
    requirements: {
      use_case: 'E-commerce fulfillment center',
      min_sf: 300000,
      max_sf: 400000,
      clear_height_min: 36,
      dock_doors_min: 60,
      power_min_amps: 4000,
      labor_pool: 'Distribution and logistics workers within 30-mile radius',
      transportation: 'Interstate access, proximity to intermodal rail, port within 100 miles',
      budget_psf: 55,
      timeline: 'Operational by Q4 2026',
    },
    recommended_markets: [
      {
        rank: 1,
        market: 'Savannah, GA — West Chatham / Bryan County',
        overall_score: 92,
        scores: {
          logistics_connectivity: 96,
          labor_availability: 88,
          cost_efficiency: 90,
          speed_to_market: 85,
          incentives: 95,
        },
        highlights: [
          'Port of Savannah: #3 US container port, 5.8M TEUs, 15% YoY growth',
          'BNSF/CSX dual rail via Mason Mega Rail Terminal',
          'I-16 / I-95 interchange — 60% of US population within 2-day truck',
          'Available 350K SF spec building at Savannah Logistics Park — $48/SF',
          'Georgia Quick Start: free workforce training for 500+ employees',
        ],
        risks: ['Hurricane zone', 'Labor competition from Amazon, Wayfair in market'],
        estimated_occupancy_cost_psf: 5.80,
        incentive_package: 'Job tax credit: $4,000/job/yr x 5 years. Property tax abatement: 10 years at 50%. Port fee rebate: $0.50/TEU for first 3 years.',
      },
      {
        rank: 2,
        market: 'Dallas-Fort Worth, TX — South Dallas / Lancaster',
        overall_score: 89,
        scores: {
          logistics_connectivity: 93,
          labor_availability: 85,
          cost_efficiency: 84,
          speed_to_market: 92,
          incentives: 88,
        },
        highlights: [
          'BNSF Alliance intermodal + UP Dallas intermodal within 40 miles',
          'DFW population 8.1M — deepest labor pool in south-central US',
          'I-20 / I-35E / I-45 tri-intersection for full south-central coverage',
          'Multiple 300K+ SF spec buildings available for immediate occupancy',
          'Texas Enterprise Fund: discretionary grants up to $5M for large employers',
        ],
        risks: ['Higher land costs ($12/SF vs $5/SF Savannah)', 'Tight industrial labor at 2.1% unemployment'],
        estimated_occupancy_cost_psf: 6.50,
        incentive_package: 'Chapter 380 agreement: property tax rebate 75% x 10 years. Texas Enterprise Fund: $3M grant for 400+ jobs. No state income tax.',
      },
      {
        rank: 3,
        market: 'Memphis, TN — Southeast Shelby County',
        overall_score: 85,
        scores: {
          logistics_connectivity: 95,
          labor_availability: 82,
          cost_efficiency: 92,
          speed_to_market: 78,
          incentives: 80,
        },
        highlights: [
          'FedEx World Hub — overnight reach to 95% of US population',
          'BNSF, UP, CSX, NS quad-rail access — best intermodal in US',
          'Lowest occupancy costs of all 4 markets at $4.90/SF',
          'Mississippi River barge access for oversized freight',
          'FastTrack infrastructure grant: up to $1M for site improvements',
        ],
        risks: ['Higher crime rates in SE Shelby deter some tenants', 'Tennessee has no major container port', 'Workforce quality concerns — 18% turnover in logistics'],
        estimated_occupancy_cost_psf: 4.90,
        incentive_package: 'PILOT: 15-year property tax freeze. FastTrack Job Training: $4,500/employee. Enhanced Job Tax Credit: $4,500/job.',
      },
      {
        rank: 4,
        market: 'Inland Empire, CA — Beaumont / San Gorgonio Pass',
        overall_score: 78,
        scores: {
          logistics_connectivity: 90,
          labor_availability: 75,
          cost_efficiency: 65,
          speed_to_market: 88,
          incentives: 72,
        },
        highlights: [
          'Ports of LA/Long Beach: #1 US container gateway, 40% of US imports',
          'Direct access to 22M consumer market in greater LA basin',
          'New spec buildings at Beaumont Logistics Park — 36\' clear, 72 docks',
          'BNSF San Bernardino intermodal within 25 miles',
        ],
        risks: ['Highest occupancy cost at $10.50/SF', 'AB 5 and CA labor regulations increase operating cost', 'Warehouse moratoriums in adjacent cities'],
        estimated_occupancy_cost_psf: 10.50,
        incentive_package: 'California Competes Tax Credit: up to $2M based on job creation. Riverside County: streamlined permitting for qualifying employers.',
      },
    ],
    recommendation: 'Top pick: Savannah, GA (West Chatham / Bryan County). Best overall score (92) driven by #1 logistics connectivity to east coast population centers, lowest all-in occupancy cost outside Memphis, and most aggressive incentive package. The available 350K SF spec building at Savannah Logistics Park at $48/SF is below budget and can be operational by Q4 2026 with 6-month fit-out. Georgia Quick Start provides free workforce training, critical for ramping 400+ distribution employees. Primary risk is hurricane exposure — mitigate with comprehensive property insurance and business continuity planning.',
  },

  portfolio_optimizer: {
    skill: 'portfolio_optimizer',
    portfolio: {
      name: 'Apex Industrial Fund II',
      total_properties: 12,
      total_sf: 1420000,
      total_value: 178500000,
      avg_cap_rate: 0.056,
      avg_occupancy: 0.94,
      walt_years: 5.8,
      annual_noi: 9996000,
    },
    holdings: [
      { property_id: 'APX-001', market: 'DFW', sf: 210000, value: 31500000, pct_of_portfolio: 0.176, asset_type: 'warehouse', tenant: 'Amazon', cap_rate: 0.048 },
      { property_id: 'APX-002', market: 'DFW', sf: 85000, value: 12500000, pct_of_portfolio: 0.070, asset_type: 'warehouse', tenant: 'FedEx Ground', cap_rate: 0.058 },
      { property_id: 'APX-003', market: 'DFW', sf: 120000, value: 16800000, pct_of_portfolio: 0.094, asset_type: 'cross_dock', tenant: 'XPO Logistics', cap_rate: 0.055 },
      { property_id: 'APX-004', market: 'Savannah', sf: 200000, value: 23000000, pct_of_portfolio: 0.129, asset_type: 'cross_dock', tenant: 'Amazon', cap_rate: 0.054 },
      { property_id: 'APX-005', market: 'Savannah', sf: 150000, value: 18750000, pct_of_portfolio: 0.105, asset_type: 'warehouse', tenant: 'Lineage Logistics', cap_rate: 0.060 },
      { property_id: 'APX-006', market: 'Memphis', sf: 95000, value: 9500000, pct_of_portfolio: 0.053, asset_type: 'warehouse', tenant: 'FedEx Freight', cap_rate: 0.068 },
      { property_id: 'APX-007', market: 'Lehigh Valley', sf: 110000, value: 15400000, pct_of_portfolio: 0.086, asset_type: 'flex', tenant: 'Multi-tenant (4)', cap_rate: 0.062 },
      { property_id: 'APX-008', market: 'Lehigh Valley', sf: 75000, value: 10500000, pct_of_portfolio: 0.059, asset_type: 'warehouse', tenant: 'Uline', cap_rate: 0.059 },
      { property_id: 'APX-009', market: 'Inland Empire', sf: 135000, value: 18900000, pct_of_portfolio: 0.106, asset_type: 'warehouse', tenant: 'Home Depot', cap_rate: 0.051 },
      { property_id: 'APX-010', market: 'Houston', sf: 90000, value: 9000000, pct_of_portfolio: 0.050, asset_type: 'flex', tenant: 'Multi-tenant (3)', cap_rate: 0.067 },
      { property_id: 'APX-011', market: 'DFW', sf: 65000, value: 5850000, pct_of_portfolio: 0.033, asset_type: 'small_bay', tenant: 'Multi-tenant (8)', cap_rate: 0.072 },
      { property_id: 'APX-012', market: 'DFW', sf: 85000, value: 6800000, pct_of_portfolio: 0.038, asset_type: 'flex', tenant: 'Multi-tenant (5)', cap_rate: 0.069 },
    ],
    concentration_analysis: {
      by_market: {
        DFW: { pct: 0.411, value: 73450000, properties: 5 },
        Savannah: { pct: 0.234, value: 41750000, properties: 2 },
        Lehigh_Valley: { pct: 0.145, value: 25900000, properties: 2 },
        Inland_Empire: { pct: 0.106, value: 18900000, properties: 1 },
        Houston: { pct: 0.050, value: 9000000, properties: 1 },
        Memphis: { pct: 0.053, value: 9500000, properties: 1 },
      },
      by_tenant: {
        Amazon: { pct: 0.305, value: 54500000, properties: 2 },
        FedEx: { pct: 0.123, value: 22000000, properties: 2 },
        multi_tenant: { pct: 0.180, value: 32150000, properties: 4 },
        other_single: { pct: 0.392, value: 69850000, properties: 4 },
      },
      concentration_score: 62,
      herfindahl_market: 0.274,
      herfindahl_tenant: 0.198,
    },
    risk_flags: [
      'DFW concentration at 41.1% — exceeds 35% single-market guideline',
      'Amazon tenant exposure at 30.5% — single-tenant concentration above 25% threshold',
      'Only 1 property each in Inland Empire, Houston, Memphis — limited diversification benefit',
      'APX-011 and APX-012 combined only 3.3% + 3.8% = 7.1% — subscale positions',
      'No Sunbelt Southeast exposure outside Savannah (no Atlanta, Charlotte, Nashville)',
    ],
    recommendations: [
      {
        action: 'Dispose APX-011 and APX-012 (DFW small bay/flex, $12.65M combined)',
        rationale: 'Subscale positions at 3.3% and 3.8% of portfolio. Sale reduces DFW concentration from 41.1% to 34.0%. Multi-tenant flex trades at 6.9-7.2% cap — strong buyer demand in current market. Redeploy proceeds into target acquisitions below.',
        priority: 'high',
        estimated_proceeds: 12650000,
      },
      {
        action: 'Acquire $12-15M NNN industrial in Charlotte or Nashville',
        rationale: 'Adds Sunbelt Southeast diversification. Charlotte and Nashville are top-5 industrial absorption markets. Fills geographic gap between Savannah and Lehigh Valley. Target 5.5-6.0% cap single-tenant with IG credit.',
        priority: 'high',
        estimated_cost: 13500000,
      },
      {
        action: 'Monitor Amazon lease expirations across APX-001 and APX-004',
        rationale: '30.5% Amazon exposure is manageable given IG credit but creates binary risk at lease rollover. Both leases have 6+ years remaining — no immediate action, but begin disposition planning for one asset at year 4 remaining.',
        priority: 'medium',
        estimated_cost: 0,
      },
    ],
    optimized_metrics: {
      projected_concentration_score: 74,
      projected_herfindahl_market: 0.215,
      projected_dfw_pct: 0.340,
      projected_market_count: 7,
      improvement: 'Concentration score improves from 62 to 74. DFW drops below 35% guideline. Market HHI improves from 0.274 to 0.215. Adding Charlotte/Nashville brings market count from 6 to 7.',
    },
  },

  news_digest: {
    skill: 'news_digest',
    digest_type: 'weekly',
    period: '2026-02-17 to 2026-02-23',
    sector: 'industrial_cre',
    sentiment: 'bullish',
    sentiment_score: 0.72,
    top_stories: [
      {
        headline: 'Prologis Acquires 2.1M SF DFW Portfolio for $315M',
        source: 'CoStar News',
        date: '2026-02-21',
        summary: 'Prologis closed on a 7-property DFW industrial portfolio at $150/SF average, a 4.8% cap rate — the tightest industrial portfolio cap rate in DFW history. Signals continued institutional conviction in DFW logistics.',
        impact: 'bullish',
        relevance_score: 0.95,
        action_items: ['Review Alliance comps against $150/SF benchmark', 'Update broker pricing guidance for DFW NNN product'],
      },
      {
        headline: 'Port of Savannah Sets Monthly Volume Record: 620K TEUs in January',
        source: 'Journal of Commerce',
        date: '2026-02-19',
        summary: 'Port of Savannah handled 620,000 TEUs in January 2026, up 18% YoY. Mason Mega Rail Terminal operating at 85% capacity. Savannah is now the #2 US container port by volume, surpassing Port of Long Beach.',
        impact: 'bullish',
        relevance_score: 0.92,
        action_items: ['Revisit Savannah pipeline — accelerating demand may absorb spec construction faster than projected'],
      },
      {
        headline: 'Amazon Announces 15 New Fulfillment Centers Nationwide for 2026',
        source: 'Reuters',
        date: '2026-02-20',
        summary: 'Amazon will open 15 new fulfillment and last-mile delivery centers in 2026, with DFW, Savannah, and Memphis on the list. Average facility size: 250,000-500,000 SF. Total investment exceeds $2.5B.',
        impact: 'bullish',
        relevance_score: 0.90,
        action_items: ['Identify land sites near announced locations for spec development', 'Review Amazon lease terms on existing portfolio assets'],
      },
      {
        headline: 'Federal Reserve Signals Two Rate Cuts in 2026, Industrial REIT Stocks Rally',
        source: 'Wall Street Journal',
        date: '2026-02-18',
        summary: 'Fed Chair indicated two 25bp rate cuts likely in H2 2026, bringing target rate to 4.0-4.25%. Industrial REITs (STAG, FR, PLD) rallied 3-5%. Lower rates will compress cap rates further and increase acquisition competition.',
        impact: 'bullish',
        relevance_score: 0.88,
        action_items: ['Lock debt pricing on pending acquisitions before rate expectations compress spreads', 'Model cap rate compression scenarios for portfolio valuations'],
      },
      {
        headline: 'Inland Empire Warehouse Moratorium Expands to Three More Cities',
        source: 'Bisnow',
        date: '2026-02-22',
        summary: 'Fontana, Colton, and Jurupa Valley join Riverside and Ontario in imposing warehouse development moratoriums. Combined impact: 12M SF of proposed projects on hold. Existing industrial buildings see 8% rent spike.',
        impact: 'mixed',
        relevance_score: 0.82,
        action_items: ['APX-009 (IE Home Depot) benefits from constrained supply — hold and monitor rent growth', 'Evaluate IE portfolio expansion via acquisition vs new development (moratorium makes acquisition-only play)'],
      },
    ],
    market_pulse: {
      industrial_vacancy_national: 0.048,
      vacancy_trend: 'rising_slowly',
      avg_asking_rent_national: 8.25,
      rent_trend: 'increasing',
      cap_rate_trend: 'compressing',
      construction_pipeline_sf: 325000000,
      net_absorption_trailing_12mo_sf: 290000000,
      supply_demand_balance: 'Supply slightly exceeds demand nationally, but top-tier markets (DFW, Savannah, Lehigh Valley) remain net-positive absorption.',
    },
    action_items: [
      'Update DFW pricing models to reflect Prologis $150/SF portfolio benchmark — current Alliance comps may be understating value',
      'Accelerate Alliance FedEx deal (DEAL-TX-001) — rate cut expectations will bring more buyers and compress caps',
      'Schedule call with Savannah broker network to discuss spec building availability before Amazon expansion announcement drives up pricing',
    ],
    sources: ['CoStar News', 'Journal of Commerce', 'Reuters', 'Wall Street Journal', 'Bisnow', 'GlobeSt', 'CBRE Research'],
  },
};
