name = "swarm-router"
main = "src/index.js"
compatibility_date = "2024-09-25"
account_id = "6abec5e82728df0610a98be9364918e4"

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "INTELLIGENCE"
bucket_name = "sb-intelligence"

[[r2_buckets]]
binding = "MEDICAL"
bucket_name = "sb-medical"

[[r2_buckets]]
binding = "AVIATION"
bucket_name = "sb-aviation"

[[r2_buckets]]
binding = "CRE"
bucket_name = "sb-cre"

[[r2_buckets]]
binding = "CORE"
bucket_name = "sb-core"

[[d1_databases]]
binding = "DB"
database_name = "swarm-intelligence-db"
database_id = "c9b84cf4-b09d-4a6e-a2d5-27ff7ed67d07"

[[vectorize]]
binding = "VECTORIZE"
index_name = "swarm-memory"

[[routes]]
pattern = "router.swarmandbee.com/*"
zone_name = "swarmandbee.com"

[[routes]]
pattern = "api.router.swarmandbee.com/*"
zone_name = "swarmandbee.com"
